modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="nomobs"
version="1.0.0"
displayName="NoMobs"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ManilBe, MCreator"

[[dependencies.nomobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



